version: '3'
services:
  coordinator:
    build: .
    hostname: coordinator
    ports:
      - "8080:8080"
    environment:
      - PRESTO_CONF_COORDINATOR=true
      - PRESTO_CONF_INCLUDE_COORDINATOR=false
      - PRESTO_CONF_DISCOVERY_URI=http://coordinator:8080
    volumes:
      - "./data/coordinator:/home/presto/data"
  worker1:
    build: 
      context: .
    environment:
      - PRESTO_CONF_COORDINATOR=false
      - PRESTO_CONF_INCLUDE_COORDINATOR=false
      - PRESTO_CONF_HTTP_PORT=18080
      - PRESTO_CONF_DISCOVERY_URI=http://coordinator:8080
    hostname: worker1
    ports:
      - "18080:18080"
    volumes:
      - "./data/worker1:/home/presto/data"
  worker2:
    build:
      context: .
    environment:
      - PRESTO_CONF_COORDINATOR=false
      - PRESTO_CONF_INCLUDE_COORDINATOR=false
      - PRESTO_CONF_HTTP_PORT=28080
      - PRESTO_CONF_DISCOVERY_URI=http://coordinator:8080
    hostname: worker2
    ports:
      - "28080:28080"
    volumes:
      - "./data/worker2:/home/presto/data"
    depends_on:
      - coordinator
  worker3:
    build: 
      context: .
    environment:
      - PRESTO_CONF_COORDINATOR=false
      - PRESTO_CONF_INCLUDE_COORDINATOR=false
      - PRESTO_CONF_HTTP_PORT=38080
      - PRESTO_CONF_DISCOVERY_URI=http://coordinator:8080
    hostname: worker3
    ports:
      - "38080:38080"
    volumes:
      - "./data/worker3:/home/presto/data"
    depends_on:
      - coordinator
      